server:
  port: 8989

spring:
  application:
    name: gateway

  cloud:
    consul:
      port: 8500
      host: localhost
      discovery:
        service-name: ${spring.application.name}
        hostname: 127.0.0.1  # 必须加该配置，不然consul找不到服务
    gateway:
      routes:
        - id: user_route
          uri: lb://users
          predicates:
            - Path=/feign/**, /user/**

        - id: product_route
          uri: lb://products  # lb： 使用负载均衡策略  products：服务名
          predicates:
            - Path=/product/**

      discovery:    # 开启获取服务名，动态获取路由地址
        locator:
          enabled: true
      metrics:
        enabled: true


management:
  endpoints:
    web:
      exposure:
        include: "*"     # 暴露路由规则web端点  /actuator/gateway/routes
